version: '3.7'
services:
  portainer:
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    port:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/docker/portainer-data:/data
    networks:
      - oueb
    